/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.controller.DBController;
import com.ada.sme.main.Main;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PaDaWaN
 */
public class AddEmployeeView extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployeeView
     */
    public AddEmployeeView() {
        initComponents();
    }

    public boolean validateInputs(int a){
        //1 buttons çalışan ekle
        //AEV_ekle ---> 1
        
        if(a==1){
            //rules
            //türkçe karakter yok
            //isim soyad ve kullanıcı adı 4-12 karakter ve küçük büyük harfler
            //parola 4-12 karakter özel karakterler, numeric alfa numerik karakterler
            if(AEV_isim.getText().matches("^[a-zA-Z]{4,12}$") &&
               AEV_soyad.getText().matches("^[a-zA-Z]{4,12}$") &&
               AEV_kullaniciadi.getText().matches("^[a-zA-Z]{4,12}$") &&
               AEV_sifre.getText().matches("^(?=.*\\d)(?=.*[a-zA-Z]).{4,12}$")){ 
                return true;
            }
            else {
                return false;
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AEV_isim = new javax.swing.JTextField();
        AEV_soyad = new javax.swing.JTextField();
        AEV_kullaniciadi = new javax.swing.JTextField();
        AEV_sifre = new javax.swing.JTextField();
        AEV_ekle = new javax.swing.JButton();
        AEV_liste = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 13), new java.awt.Dimension(0, 13), new java.awt.Dimension(32767, 13));

        setBackground(new java.awt.Color(227, 227, 227));
        setMaximumSize(new java.awt.Dimension(646, 500));
        setMinimumSize(new java.awt.Dimension(646, 500));
        setPreferredSize(new java.awt.Dimension(646, 500));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 2, 0};
        layout.rowHeights = new int[] {0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0};
        setLayout(layout);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Yeni Çalışan Ekle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 80, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Çalışan İsmi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(jLabel3, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Çalışan Soyadı:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Kullanıcı Adı:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Şifre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        add(jLabel6, gridBagConstraints);

        AEV_isim.setMaximumSize(new java.awt.Dimension(170, 28));
        AEV_isim.setMinimumSize(new java.awt.Dimension(170, 28));
        AEV_isim.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(AEV_isim, gridBagConstraints);

        AEV_soyad.setMaximumSize(new java.awt.Dimension(170, 28));
        AEV_soyad.setMinimumSize(new java.awt.Dimension(170, 28));
        AEV_soyad.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(AEV_soyad, gridBagConstraints);

        AEV_kullaniciadi.setMaximumSize(new java.awt.Dimension(170, 28));
        AEV_kullaniciadi.setMinimumSize(new java.awt.Dimension(170, 28));
        AEV_kullaniciadi.setPreferredSize(new java.awt.Dimension(170, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(AEV_kullaniciadi, gridBagConstraints);

        AEV_sifre.setMaximumSize(new java.awt.Dimension(170, 28));
        AEV_sifre.setMinimumSize(new java.awt.Dimension(170, 28));
        AEV_sifre.setPreferredSize(new java.awt.Dimension(170, 28));
        AEV_sifre.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(AEV_sifre, gridBagConstraints);

        AEV_ekle.setBackground(new java.awt.Color(67, 149, 195));
        AEV_ekle.setForeground(new java.awt.Color(254, 254, 254));
        AEV_ekle.setText("Çalışan Ekle");
        AEV_ekle.setMaximumSize(new java.awt.Dimension(120, 35));
        AEV_ekle.setMinimumSize(new java.awt.Dimension(120, 35));
        AEV_ekle.setPreferredSize(new java.awt.Dimension(120, 35));
        AEV_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEV_ekleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(AEV_ekle, gridBagConstraints);

        AEV_liste.setBackground(new java.awt.Color(67, 149, 195));
        AEV_liste.setForeground(new java.awt.Color(254, 254, 254));
        AEV_liste.setText("Çalışan Listesi");
        AEV_liste.setMaximumSize(new java.awt.Dimension(150, 35));
        AEV_liste.setMinimumSize(new java.awt.Dimension(150, 35));
        AEV_liste.setPreferredSize(new java.awt.Dimension(150, 35));
        AEV_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEV_listeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 0);
        add(AEV_liste, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        add(filler1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void AEV_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEV_ekleActionPerformed
        if(validateInputs(1)){
        
        DBController dbcontroller = new DBController();
        int emp_id = DBController.getLastID("SELECT * from employee order by id DESC");
        System.out.print(emp_id + "");
        dbcontroller.empInsDelUpDB("INSERT INTO employee VALUES(" + (emp_id + 1) + ", '" + AEV_isim.getText() + "', '" + AEV_soyad.getText() + "', '" + AEV_kullaniciadi.getText() + "', '" + AEV_sifre.getText() + "')");
        
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(new ManageEmployeeView());
        MainFrame.main_anapanel.validate();
        
        Main.logger(AEV_isim.getText() + " " + AEV_soyad.getText() + " isimli satıcı oluşturuldu.");
        
         } else {
            //REGEX geçemedi
            JOptionPane.showMessageDialog(null,"Lütfen girmiş olduğunuz alanları kontrol ediniz.\n"
                  + "Kurallar:\n"
                    + "Türkçe karakter kullanmayınız (ş,ç,ı,ü,ğ,ö,İ,Ş,Ç,Ö,Ğ,Ü)\n"
                  + "İsim , Soyad ve Kullanıcı adı 4-12 karakter ve sadece küçük büyük harfler olabilir,\n"
                    + "Şifre 4-12 karakter küçük büyük harfler, rakamlar ve özel karakterler  olabilir.\n"
                    + "en az 1 sayı içermesi gerekir.",
                  "Hatalı Giriş Yaptınız!!!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_AEV_ekleActionPerformed

    private void AEV_listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEV_listeActionPerformed
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(new ManageEmployeeView());
        MainFrame.main_anapanel.validate();
        
    }//GEN-LAST:event_AEV_listeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AEV_ekle;
    private javax.swing.JTextField AEV_isim;
    private javax.swing.JTextField AEV_kullaniciadi;
    private javax.swing.JButton AEV_liste;
    private javax.swing.JTextField AEV_sifre;
    private javax.swing.JTextField AEV_soyad;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
