/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.model.StatusModel;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author PaDaWaN
 */
public class MainFrame extends javax.swing.JFrame {

    StatusModel sm;
    static int pingFlag = 0;
    final int SLEEPTIME = 5000;
    final String IPADDRESS = "139.179.139.112";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        main_solpanel.removeAll();
        main_solpanel.add(new StoreLeftPanelView(this));
        sm = new StatusModel(IPADDRESS);

       // new Thread(new runCheck()).start();



    }

    public void setLeftPanel(JPanel p) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        main_durum = new javax.swing.JButton();
        main_magaza = new javax.swing.JButton();
        main_online_market = new javax.swing.JButton();
        main_stok = new javax.swing.JButton();
        main_destek = new javax.swing.JButton();
        main_solpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main_anapanel = new javax.swing.JPanel();
        main_status_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(227, 227, 227));
        setMinimumSize(new java.awt.Dimension(805, 600));
        setPreferredSize(new java.awt.Dimension(805, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        main_durum.setBackground(new java.awt.Color(67, 149, 195));
        main_durum.setForeground(new java.awt.Color(254, 254, 254));
        main_durum.setText("Anasayfa");
        main_durum.setMaximumSize(new java.awt.Dimension(60, 70));
        main_durum.setMinimumSize(new java.awt.Dimension(60, 70));
        main_durum.setPreferredSize(new java.awt.Dimension(60, 70));
        main_durum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_durumActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_durum, gridBagConstraints);

        main_magaza.setBackground(new java.awt.Color(67, 149, 195));
        main_magaza.setForeground(new java.awt.Color(254, 254, 254));
        main_magaza.setText("Mağaza");
        main_magaza.setMaximumSize(new java.awt.Dimension(65, 70));
        main_magaza.setMinimumSize(new java.awt.Dimension(65, 70));
        main_magaza.setPreferredSize(new java.awt.Dimension(65, 70));
        main_magaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_magazaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_magaza, gridBagConstraints);

        main_online_market.setBackground(new java.awt.Color(67, 149, 195));
        main_online_market.setForeground(new java.awt.Color(254, 254, 254));
        main_online_market.setText("Online Market");
        main_online_market.setMaximumSize(new java.awt.Dimension(111, 70));
        main_online_market.setMinimumSize(new java.awt.Dimension(111, 70));
        main_online_market.setPreferredSize(new java.awt.Dimension(111, 70));
        main_online_market.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_online_marketActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_online_market, gridBagConstraints);

        main_stok.setBackground(new java.awt.Color(67, 149, 195));
        main_stok.setForeground(new java.awt.Color(254, 254, 254));
        main_stok.setText("Stok");
        main_stok.setMaximumSize(new java.awt.Dimension(43, 70));
        main_stok.setMinimumSize(new java.awt.Dimension(43, 70));
        main_stok.setPreferredSize(new java.awt.Dimension(43, 70));
        main_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_stokActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_stok, gridBagConstraints);

        main_destek.setBackground(new java.awt.Color(67, 149, 195));
        main_destek.setForeground(new java.awt.Color(254, 254, 254));
        main_destek.setText("Destek");
        main_destek.setMaximumSize(new java.awt.Dimension(62, 70));
        main_destek.setMinimumSize(new java.awt.Dimension(62, 70));
        main_destek.setPreferredSize(new java.awt.Dimension(62, 70));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_destek, gridBagConstraints);

        main_solpanel.setBackground(new java.awt.Color(227, 227, 227));
        main_solpanel.setMaximumSize(new java.awt.Dimension(150, 2147));
        main_solpanel.setMinimumSize(new java.awt.Dimension(150, 200));
        main_solpanel.setPreferredSize(new java.awt.Dimension(150, 200));
        main_solpanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(main_solpanel, gridBagConstraints);

        jLabel1.setText("jLabel1asdasdads");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel1, gridBagConstraints);

        main_anapanel.setBackground(new java.awt.Color(227, 227, 227));
        main_anapanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(main_anapanel, gridBagConstraints);

        main_status_panel.setBackground(new java.awt.Color(227, 227, 227));
        main_status_panel.setMaximumSize(new java.awt.Dimension(32767, 20));
        main_status_panel.setMinimumSize(new java.awt.Dimension(100, 20));
        main_status_panel.setPreferredSize(new java.awt.Dimension(200, 20));

        javax.swing.GroupLayout main_status_panelLayout = new javax.swing.GroupLayout(main_status_panel);
        main_status_panel.setLayout(main_status_panelLayout);
        main_status_panelLayout.setHorizontalGroup(
            main_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1055, Short.MAX_VALUE)
        );
        main_status_panelLayout.setVerticalGroup(
            main_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(main_status_panel, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/logo.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_durumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_durumActionPerformed
    }//GEN-LAST:event_main_durumActionPerformed

    private void main_magazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_magazaActionPerformed
        main_solpanel.removeAll();
        main_solpanel.add(new StoreLeftPanelView(this));
        main_solpanel.validate();
        
        main_anapanel.removeAll();
        main_anapanel.add(new ManageEmployeeView());
        main_anapanel.validate();
    }//GEN-LAST:event_main_magazaActionPerformed

    private void main_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_stokActionPerformed
        main_solpanel.removeAll();
        main_solpanel.add(new StockLeftPanelView(this));
        main_solpanel.validate();
        
        main_anapanel.removeAll();
        main_anapanel.add(new ManageStockView());
        main_anapanel.validate();
    }//GEN-LAST:event_main_stokActionPerformed

    private void main_online_marketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_online_marketActionPerformed
        // TODO add your handling code here:
        main_solpanel.removeAll();
        main_solpanel.add(new JPanel());
        main_solpanel.validate();
        
        main_anapanel.removeAll();
        main_anapanel.add(new OnlineStoreView());
        main_anapanel.validate();
    }//GEN-LAST:event_main_online_marketActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  /*      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               /* MainFrame mf = new MainFrame();

                mf.setVisible(true);*/


     /*       }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel main_anapanel;
    private javax.swing.JButton main_destek;
    private javax.swing.JButton main_durum;
    private javax.swing.JButton main_magaza;
    private javax.swing.JButton main_online_market;
    private javax.swing.JPanel main_solpanel;
    private javax.swing.JPanel main_status_panel;
    private javax.swing.JButton main_stok;
    // End of variables declaration//GEN-END:variables

    class runCheck implements Runnable {

        @Override
        public void run() {
            String urlString = "http://ozguryazilim.bilkent.edu.tr/open/ping.php?id=22";
            URL url = null;
            URLConnection conn = null;
            InputStream is;
            try {
                url = new URL(urlString);
                
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            while (true) {
                try {
                    sm.check();
                    boolean ans = sm.getStatus();

                    if (ans) {
                        System.out.println("ulasiliyor");

                    } else if (!ans) {
                        System.out.println("ulasilmiyor");
                    }


                    if((pingFlag%4)==0){
                    conn = url.openConnection();
                    is = conn.getInputStream();
                    }

                    Thread.sleep(SLEEPTIME);
                    pingFlag++;
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
