/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.main.Main;
import static com.ada.sme.main.Main.file1;
import com.ada.sme.model.StatusModel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

public class MainFrame extends javax.swing.JFrame {

    StatusModel sm;
    static int pingFlag = 0;
    static int statusNormalizer = 0;
    public static boolean uploading = false;
    final int SLEEPTIME = 5000;
    final String IPADDRESS = "139.179.139.112";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        //open frame at the center of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);


        //which window will be opened settings
        main_solpanel.removeAll();
        main_solpanel.add(new MainPageLeftPanelView());
        sm = new StatusModel(IPADDRESS);

        clear_buttons();
        main_anasayfa.setBackground(new Color(41, 66, 80));
        main_anapanel.add(new MainPagePanelView());

        new Thread(new runCheck()).start();
    }

    public void clear_buttons() {
        main_anasayfa.setBackground(new Color(67, 149, 195));
        main_magaza.setBackground(new Color(67, 149, 195));
        main_online_market.setBackground(new Color(67, 149, 195));
        main_stok.setBackground(new Color(67, 149, 195));
       
    }

    public static void callOnlineAgain() {

        main_anapanel.removeAll();
        main_anapanel.add(new OnlineStoreView());
        main_anapanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        main_anasayfa = new javax.swing.JButton();
        main_magaza = new javax.swing.JButton();
        main_online_market = new javax.swing.JButton();
        main_stok = new javax.swing.JButton();
        main_solpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main_anapanel = new javax.swing.JPanel();
        main_status_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kobilere Özgürlük");
        setBackground(new java.awt.Color(227, 227, 227));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        main_anasayfa.setBackground(new java.awt.Color(67, 149, 195));
        main_anasayfa.setForeground(new java.awt.Color(254, 254, 254));
        main_anasayfa.setText("Anasayfa");
        main_anasayfa.setMaximumSize(new java.awt.Dimension(60, 70));
        main_anasayfa.setMinimumSize(new java.awt.Dimension(60, 70));
        main_anasayfa.setPreferredSize(new java.awt.Dimension(60, 70));
        main_anasayfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_anasayfaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_anasayfa, gridBagConstraints);

        main_magaza.setBackground(new java.awt.Color(67, 149, 195));
        main_magaza.setForeground(new java.awt.Color(254, 254, 254));
        main_magaza.setText("Mağaza");
        main_magaza.setMaximumSize(new java.awt.Dimension(65, 70));
        main_magaza.setMinimumSize(new java.awt.Dimension(65, 70));
        main_magaza.setPreferredSize(new java.awt.Dimension(65, 70));
        main_magaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_magazaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_magaza, gridBagConstraints);

        main_online_market.setBackground(new java.awt.Color(67, 149, 195));
        main_online_market.setForeground(new java.awt.Color(254, 254, 254));
        main_online_market.setText("Sipariş Takibi");
        main_online_market.setMaximumSize(new java.awt.Dimension(111, 70));
        main_online_market.setMinimumSize(new java.awt.Dimension(111, 70));
        main_online_market.setPreferredSize(new java.awt.Dimension(111, 70));
        main_online_market.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_online_marketActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_online_market, gridBagConstraints);

        main_stok.setBackground(new java.awt.Color(67, 149, 195));
        main_stok.setForeground(new java.awt.Color(254, 254, 254));
        main_stok.setText("Stok");
        main_stok.setMaximumSize(new java.awt.Dimension(43, 70));
        main_stok.setMinimumSize(new java.awt.Dimension(43, 70));
        main_stok.setPreferredSize(new java.awt.Dimension(43, 70));
        main_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_stokActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        getContentPane().add(main_stok, gridBagConstraints);

        main_solpanel.setBackground(new java.awt.Color(227, 227, 227));
        main_solpanel.setMaximumSize(new java.awt.Dimension(150, 600));
        main_solpanel.setMinimumSize(new java.awt.Dimension(150, 600));
        main_solpanel.setPreferredSize(new java.awt.Dimension(150, 600));
        main_solpanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(main_solpanel, gridBagConstraints);

        jLabel1.setText("jLabel1asdasdads");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel1, gridBagConstraints);

        main_anapanel.setBackground(new java.awt.Color(227, 227, 227));
        main_anapanel.setMaximumSize(new java.awt.Dimension(1024, 768));
        main_anapanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        main_anapanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        main_anapanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(main_anapanel, gridBagConstraints);

        main_status_panel.setBackground(new java.awt.Color(227, 227, 227));
        main_status_panel.setMaximumSize(new java.awt.Dimension(32767, 20));
        main_status_panel.setMinimumSize(new java.awt.Dimension(100, 20));
        main_status_panel.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Sistem Durumu:");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/button-red.png"))); // NOI18N

        jLabel7.setText("Senkronizasyon:");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/button-red.png"))); // NOI18N

        javax.swing.GroupLayout main_status_panelLayout = new javax.swing.GroupLayout(main_status_panel);
        main_status_panel.setLayout(main_status_panelLayout);
        main_status_panelLayout.setHorizontalGroup(
            main_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_status_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(824, Short.MAX_VALUE))
        );
        main_status_panelLayout.setVerticalGroup(
            main_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_status_panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(main_status_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(62, 62, 62))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(main_status_panel, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/Untitled.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main_anasayfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_anasayfaActionPerformed
        main_solpanel.removeAll();
        main_solpanel.add(new MainPageLeftPanelView());
        main_solpanel.validate();



        main_anapanel.removeAll();
        main_anapanel.add(new MainPagePanelView());
        main_anapanel.validate();


        main_anapanel.updateUI();

        clear_buttons();
        main_anasayfa.setBackground(new Color(41, 66, 80));
    }//GEN-LAST:event_main_anasayfaActionPerformed

    private void main_magazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_magazaActionPerformed
        main_solpanel.removeAll();
        main_solpanel.add(new StoreLeftPanelView(this));
        main_solpanel.validate();



        main_anapanel.removeAll();
        main_anapanel.add(new SaleProductPanelView());
        main_anapanel.validate();


        main_anapanel.updateUI();

        clear_buttons();
        main_magaza.setBackground(new Color(41, 66, 80));
    }//GEN-LAST:event_main_magazaActionPerformed

    private void main_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_stokActionPerformed
        main_solpanel.removeAll();
        main_solpanel.add(new StockLeftPanelView(this));
        main_solpanel.validate();

        main_anapanel.removeAll();
        main_anapanel.add(new ManageStockView());
        main_anapanel.validate();
        main_anapanel.updateUI();
        clear_buttons();
        main_stok.setBackground(new Color(41, 66, 80));
    }//GEN-LAST:event_main_stokActionPerformed

    private void main_online_marketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_online_marketActionPerformed
        main_solpanel.removeAll();
        main_solpanel.add(new OnlineStoreLeftPanelView());
        main_solpanel.validate();

        main_anapanel.removeAll();
        main_anapanel.add(new OnlineStoreView());
        main_anapanel.validate();
        main_anapanel.updateUI();
        clear_buttons();
        main_online_market.setBackground(new Color(41, 66, 80));
    }//GEN-LAST:event_main_online_marketActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
     /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*      try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form */
    /*   java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     /* MainFrame mf = new MainFrame();

     mf.setVisible(true);*/
    /*       }
     });
     }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel main_anapanel;
    private javax.swing.JButton main_anasayfa;
    private javax.swing.JButton main_magaza;
    private javax.swing.JButton main_online_market;
    private javax.swing.JPanel main_solpanel;
    private javax.swing.JPanel main_status_panel;
    private javax.swing.JButton main_stok;
    // End of variables declaration//GEN-END:variables

    class runCheck implements Runnable {

        @Override
        public void run() {
            String urlString = "http://ozguryazilim.bilkent.edu.tr/open/ping.php?id=22";
            URL url = null;
            URLConnection conn = null;
            InputStream is;
            try {
                url = new URL(urlString);

            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

            while (true) {
                try {
                    Thread.sleep(SLEEPTIME);
                    System.out.println("Image: " + Main.file1.length());
                    boolean ans = sm.check();

                    if (ans) {
                        statusNormalizer = 0;
                        System.out.println("ulasiliyor");
                        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/button-green.png")));
                        if (Main.temp_sql.length() > 0) {
                            Main.read();
                        }
                        if (!uploading && Main.file1.length() > 0) {
                            System.err.println("Uploading-Thread");
                            Main.imageUpload();
                        }

                    } else if (!ans) {
                        statusNormalizer++;
                        if (statusNormalizer > 2) {
                            System.out.println("ulasilmiyor");
                            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/button-red.png")));
                        }
                    }
                    if (Main.temp_sql.length() > 0) {
                        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/button-red.png")));
                    } else {
                        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ada/sme/material/button-green.png")));
                    }

                    if ((pingFlag % 4) == 0) {
                        conn = url.openConnection();
                        is = conn.getInputStream();
                    }





                    pingFlag++;
                } catch (Exception e) {
                    // e.printStackTrace();
                }
            }
        }
    }
}
