/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.controller.DBController;
import com.ada.sme.controller.ManageEmployeeController;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.drda.NetworkServerControl;

/**
 *
 * @author PaDaWaN
 */
public class ManageStockView extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeView
     */
    MainFrame frame;
    
    public ManageStockView() {
        initComponents();
        
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        
        dtm=dbController.selectDB("SELECT product.product_id,model,quantity,image,price,status FROM product");
        System.out.println(dtm);
        
        MSV_list1.setModel(dtm);
        
        ArrayList meta = dbController.fillCombo("SELECT * FROM product");
        
        MEV_identifier.addItem(meta.get(0).toString());
        MEV_identifier.addItem(meta.get(1).toString());
        MEV_identifier.addItem(meta.get(2).toString());
        MEV_identifier.addItem(meta.get(3).toString());
 
        
    }
    
    
    
    public void getnPrintAllData(ResultSet res){
        
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MEV_value = new javax.swing.JTextField();
        MEV_identifier = new javax.swing.JComboBox();
        MSV_ara = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MSV_list1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(227, 227, 227));
        setMinimumSize(new java.awt.Dimension(400, 120));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.GridBagLayout());

        MEV_value.setMaximumSize(new java.awt.Dimension(100, 28));
        MEV_value.setMinimumSize(new java.awt.Dimension(100, 28));
        MEV_value.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 0, 0);
        add(MEV_value, gridBagConstraints);

        MEV_identifier.setMaximumSize(new java.awt.Dimension(100, 28));
        MEV_identifier.setMinimumSize(new java.awt.Dimension(100, 28));
        MEV_identifier.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 12, 0, 0);
        add(MEV_identifier, gridBagConstraints);

        MSV_ara.setBackground(new java.awt.Color(67, 149, 195));
        MSV_ara.setForeground(new java.awt.Color(254, 254, 254));
        MSV_ara.setText("Ürün Ara");
        MSV_ara.setMaximumSize(new java.awt.Dimension(110, 50));
        MSV_ara.setMinimumSize(new java.awt.Dimension(110, 50));
        MSV_ara.setPreferredSize(new java.awt.Dimension(110, 50));
        MSV_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSV_araActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(MSV_ara, gridBagConstraints);

        MSV_list1.setModel(MSV_list1.getModel());
        MSV_list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MSV_list1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MSV_list1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void MSV_list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list1MouseClicked
        String id = MSV_list1.getValueAt(MSV_list1.getSelectedRow(), 0).toString();
        UpdateStockPanelView updateStockPanelView=new UpdateStockPanelView(id);
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(updateStockPanelView);
        MainFrame.main_anapanel.validate();
        
    }//GEN-LAST:event_MSV_list1MouseClicked

    private void MSV_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSV_araActionPerformed
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        if(MEV_identifier.getSelectedItem().toString().equals("product_id"))
            dtm=dbController.selectDB("SELECT * FROM product WHERE "+MEV_identifier.getSelectedItem().toString()+"="+MEV_value.getText());
        else
            dtm=dbController.selectDB("SELECT * FROM product WHERE "+MEV_identifier.getSelectedItem().toString()+" LIKE '%"+MEV_value.getText()+"%'");
        
        System.out.println(dtm);
        
        MSV_list1.setModel(dtm);
    }//GEN-LAST:event_MSV_araActionPerformed

    private void MSV_list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MSV_list2MouseClicked

    private void MSV_list3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MSV_list3MouseClicked

    private void MSV_list4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MSV_list4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MEV_identifier;
    private javax.swing.JTextField MEV_value;
    private javax.swing.JButton MSV_ara;
    private javax.swing.JTable MSV_list1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
