/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.controller.DBController;
import com.ada.sme.controller.ManageEmployeeController;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.drda.NetworkServerControl;

/**
 *
 * @author PaDaWaN
 */
public class ManageStockView extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeView
     */
    MainFrame frame;
    
    public ManageStockView() {
        initComponents();
        
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        
        dtm=dbController.selectDB("SELECT * FROM product");
        System.out.println(dtm);
        
        MSV_list1.setModel(dtm);
        
        ManageEmployeeController manageEmployeecontroller=new ManageEmployeeController();
        
        /*ArrayList meta = manageEmployeecontroller.fillCombo();
        
        MEV_identifier.addItem(meta.get(0).toString());
        MEV_identifier.addItem(meta.get(1).toString());
        MEV_identifier.addItem(meta.get(2).toString());
        MEV_identifier.addItem(meta.get(3).toString());*/
        
        dtm=dbController.selectDB("SELECT * FROM product");
        System.out.println(dtm);
        
        MSV_list2.setModel(dtm);
        
        /*
        
        dtm=dbController.selectDB("SELECT * FROM product_option");
        System.out.println(dtm);
        
        MSV_list3.setModel(dtm);
        
        
        
        
        
        dtm=dbController.selectDB("SELECT * FROM product_option_value");
        System.out.println(dtm);
        
        MSV_list4.setModel(dtm);
        */
 
        
    }
    
    
    
    public void getnPrintAllData(ResultSet res){
        
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MEV_value = new javax.swing.JTextField();
        MEV_identifier = new javax.swing.JComboBox();
        MEV_seach = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MSV_list1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        MSV_list2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        MSV_list3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        MSV_list4 = new javax.swing.JTable();

        MEV_seach.setText("Çalışan Ara");
        MEV_seach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEV_seachActionPerformed(evt);
            }
        });

        MSV_list1.setModel(MSV_list1.getModel());
        MSV_list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MSV_list1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MSV_list1);

        MSV_list2.setModel(MSV_list1.getModel());
        MSV_list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MSV_list2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(MSV_list2);

        MSV_list3.setModel(MSV_list1.getModel());
        MSV_list3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MSV_list3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(MSV_list3);

        MSV_list4.setModel(MSV_list1.getModel());
        MSV_list4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MSV_list4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(MSV_list4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MEV_value, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MEV_identifier, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MEV_seach, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MEV_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEV_identifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEV_seach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MSV_list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list1MouseClicked
        String id = MSV_list1.getValueAt(MSV_list1.getSelectedRow(), 0).toString();
        UpdateEmployeeView updateemployeeView=new UpdateEmployeeView(id);
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(updateemployeeView);
        MainFrame.main_anapanel.validate();
        
    }//GEN-LAST:event_MSV_list1MouseClicked

    private void MEV_seachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEV_seachActionPerformed
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        if(MEV_identifier.getSelectedItem().toString().equals("ID"))
            dtm=dbController.selectDB("SELECT * FROM employee WHERE "+MEV_identifier.getSelectedItem().toString()+"="+MEV_value.getText());
        else
            dtm=dbController.selectDB("SELECT * FROM employee WHERE "+MEV_identifier.getSelectedItem().toString()+" LIKE '%"+MEV_value.getText()+"%'");
        
        System.out.println(dtm);
        
        MSV_list1.setModel(dtm);
    }//GEN-LAST:event_MEV_seachActionPerformed

    private void MSV_list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MSV_list2MouseClicked

    private void MSV_list3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MSV_list3MouseClicked

    private void MSV_list4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MSV_list4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MSV_list4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MEV_identifier;
    private javax.swing.JButton MEV_seach;
    private javax.swing.JTextField MEV_value;
    private javax.swing.JTable MSV_list1;
    private javax.swing.JTable MSV_list2;
    private javax.swing.JTable MSV_list3;
    private javax.swing.JTable MSV_list4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
