/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.controller.DBController;
import com.ada.sme.controller.ManageEmployeeController;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.drda.NetworkServerControl;

/**
 *
 * @author PaDaWaN
 */
public class ManageEmployeeView extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeView
     */
    MainFrame frame;
    
    public ManageEmployeeView() {
        initComponents();
        
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        
        dtm=dbController.selectDB("SELECT * FROM employee");
        System.out.println(dtm);
        
        MEV_list.setModel(dtm);
        
        ManageEmployeeController manageEmployeecontroller=new ManageEmployeeController();
        
        ArrayList meta = manageEmployeecontroller.fillCombo();
        
        MEV_identifier.addItem(meta.get(0).toString());
        MEV_identifier.addItem(meta.get(1).toString());
        MEV_identifier.addItem(meta.get(2).toString());
        MEV_identifier.addItem(meta.get(3).toString());
 
        
    }
    
    
    
    public void getnPrintAllData(ResultSet res){
        
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MEV_value = new javax.swing.JTextField();
        MEV_identifier = new javax.swing.JComboBox();
        MEV_seach = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MEV_list = new javax.swing.JTable();

        MEV_seach.setText("Çalışan Ara");
        MEV_seach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEV_seachActionPerformed(evt);
            }
        });

        MEV_list.setModel(MEV_list.getModel());
        MEV_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MEV_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MEV_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MEV_value, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MEV_identifier, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MEV_seach, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MEV_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEV_identifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEV_seach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MEV_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEV_listMouseClicked
        String id = MEV_list.getValueAt(MEV_list.getSelectedRow(), 0).toString();
        UpdateEmployeeView updateemployeeView=new UpdateEmployeeView(id);
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(updateemployeeView);
        MainFrame.main_anapanel.validate();
        
    }//GEN-LAST:event_MEV_listMouseClicked

    private void MEV_seachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEV_seachActionPerformed
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        if(MEV_identifier.getSelectedItem().toString().equals("ID"))
            dtm=dbController.selectDB("SELECT * FROM employee WHERE "+MEV_identifier.getSelectedItem().toString()+"="+MEV_value.getText());
        else
            dtm=dbController.selectDB("SELECT * FROM employee WHERE "+MEV_identifier.getSelectedItem().toString()+" LIKE '%"+MEV_value.getText()+"%'");
        
        System.out.println(dtm);
        
        MEV_list.setModel(dtm);
    }//GEN-LAST:event_MEV_seachActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MEV_identifier;
    private javax.swing.JTable MEV_list;
    private javax.swing.JButton MEV_seach;
    private javax.swing.JTextField MEV_value;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
