/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.controller.DBController;
import com.ada.sme.controller.ManageEmployeeController;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.drda.NetworkServerControl;

/**
 *
 * @author PaDaWaN
 */
public class ManageEmployeeView extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeView
     */
    MainFrame frame;
    
    public ManageEmployeeView() {
        initComponents();
        
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        
        dtm=dbController.selectDB("SELECT * FROM employee");
        System.out.println(dtm);
        
        MEV_list.setModel(dtm);
        
        ArrayList meta = dbController.fillCombo("SELECT * FROM employee");
        
        MEV_identifier.addItem(meta.get(0).toString());
        MEV_identifier.addItem(meta.get(1).toString());
        MEV_identifier.addItem(meta.get(2).toString());
        MEV_identifier.addItem(meta.get(3).toString());
 
        
    }
    
    
    
    public void getnPrintAllData(ResultSet res){
        
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MEV_value = new javax.swing.JTextField();
        MEV_identifier = new javax.swing.JComboBox();
        MEV_seach = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MEV_list = new javax.swing.JTable();

        setBackground(new java.awt.Color(227, 227, 227));
        setLayout(new java.awt.GridBagLayout());

        MEV_value.setMaximumSize(new java.awt.Dimension(100, 28));
        MEV_value.setMinimumSize(new java.awt.Dimension(100, 28));
        MEV_value.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        add(MEV_value, gridBagConstraints);

        MEV_identifier.setMaximumSize(new java.awt.Dimension(100, 28));
        MEV_identifier.setMinimumSize(new java.awt.Dimension(100, 28));
        MEV_identifier.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        add(MEV_identifier, gridBagConstraints);

        MEV_seach.setBackground(new java.awt.Color(67, 149, 195));
        MEV_seach.setForeground(new java.awt.Color(254, 254, 254));
        MEV_seach.setText("Çalışan Ara");
        MEV_seach.setMaximumSize(new java.awt.Dimension(87, 50));
        MEV_seach.setMinimumSize(new java.awt.Dimension(87, 50));
        MEV_seach.setPreferredSize(new java.awt.Dimension(87, 50));
        MEV_seach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEV_seachActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 12);
        add(MEV_seach, gridBagConstraints);

        MEV_list.setModel(MEV_list.getModel());
        MEV_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MEV_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MEV_list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void MEV_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEV_listMouseClicked
        String id = MEV_list.getValueAt(MEV_list.getSelectedRow(), 0).toString();
        UpdateEmployeeView updateemployeeView=new UpdateEmployeeView(id);
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(updateemployeeView);
        MainFrame.main_anapanel.validate();
        
    }//GEN-LAST:event_MEV_listMouseClicked

    private void MEV_seachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEV_seachActionPerformed
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        if(MEV_identifier.getSelectedItem().toString().equals("ID"))
            dtm=dbController.selectDB("SELECT * FROM employee WHERE "+MEV_identifier.getSelectedItem().toString()+"="+MEV_value.getText());
        else
            dtm=dbController.selectDB("SELECT * FROM employee WHERE "+MEV_identifier.getSelectedItem().toString()+" LIKE '%"+MEV_value.getText()+"%'");
        
        System.out.println(dtm);
        
        MEV_list.setModel(dtm);
    }//GEN-LAST:event_MEV_seachActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MEV_identifier;
    private javax.swing.JTable MEV_list;
    private javax.swing.JButton MEV_seach;
    private javax.swing.JTextField MEV_value;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
