/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.controller.DBController;
import com.ada.sme.controller.ManageEmployeeController;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.drda.NetworkServerControl;

/**
 *
 * @author PaDaWaN
 */
public class OnlineStoreView extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmployeeView
     */
    MainFrame frame;
    
    public OnlineStoreView() {
        initComponents();
        
        DBController dbController = new DBController();
        DefaultTableModel dtm;
        
        dtm=dbController.selectDB("SELECT order_id, firstname, lastname, total, order_status_id, date_modified FROM order_t");
        System.out.println("firstSelect");
        if(dtm.getRowCount()==0){
        dtm = dbController.selectDBFromOnline("Select order_id, customer_id, firstname, lastname, email, telephone, fax, payment_firstname, payment_lastname, payment_company, payment_address_1, payment_address_2, payment_city, payment_postcode , payment_country, payment_zone, payment_method, shipping_firstname, shipping_lastname, shipping_company, shipping_address_1, shipping_address_2, shipping_city, shipping_postcode, shipping_country, shipping_zone, comment, total, order_status_id, currency_code, date_added, date_modified from oc_order");          
        }else{
             int id = DBController.getLastID("SELECT * from order_t order by order_id DESC");
             System.out.println(id+"");
             dtm = dbController.selectDBFromOnline("Select order_id, customer_id, firstname, lastname, email, telephone, fax, payment_firstname, payment_lastname, payment_company, payment_address_1, payment_address_2, payment_city, payment_postcode , payment_country, payment_zone, payment_method, shipping_firstname, shipping_lastname, shipping_company, shipping_address_1, shipping_address_2, shipping_city, shipping_postcode, shipping_country, shipping_zone, comment, total, order_status_id, currency_code, date_added, date_modified from oc_order WHERE order_id>"+id);          
             
        }
        MEV_list.setModel(dtm);
        
      /*  ArrayList meta = dbController.fillCombo("SELECT * FROM order_t");
        
        MEV_identifier.addItem(meta.get(0).toString());
        MEV_identifier.addItem(meta.get(1).toString());
        MEV_identifier.addItem(meta.get(2).toString());
        MEV_identifier.addItem(meta.get(3).toString());*/
 
        
    }
    
    
    
    public void getnPrintAllData(ResultSet res){
        
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        MEV_list = new javax.swing.JTable();

        setBackground(new java.awt.Color(227, 227, 227));
        setMaximumSize(new java.awt.Dimension(646, 500));
        setMinimumSize(new java.awt.Dimension(646, 500));
        setPreferredSize(new java.awt.Dimension(646, 500));
        setLayout(new java.awt.GridBagLayout());

        MEV_list.setModel(MEV_list.getModel());
        MEV_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MEV_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MEV_list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void MEV_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MEV_listMouseClicked
        String id = MEV_list.getValueAt(MEV_list.getSelectedRow(), 0).toString();
        OrderView orderView=new OrderView(id);        
        orderView.setVisible(true);
       /* MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(orderView);
        MainFrame.main_anapanel.validate();*/
        
    }//GEN-LAST:event_MEV_listMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MEV_list;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
