/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

/**
 *
 * @author PaDaWaN
 */
public class StockLeftPanelView extends javax.swing.JPanel {

    /**
     * Creates new form StatusLeftPanelView
     */
    MainFrame frame;
    public StockLeftPanelView(MainFrame main) {
        initComponents();
        frame= main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SLPV_ekle = new javax.swing.JButton();
        SLPV_yonet = new javax.swing.JButton();

        setBackground(new java.awt.Color(227, 227, 227));
        setMaximumSize(new java.awt.Dimension(146, 2000));
        setMinimumSize(new java.awt.Dimension(146, 250));
        setPreferredSize(new java.awt.Dimension(146, 250));
        setLayout(new java.awt.GridBagLayout());

        SLPV_ekle.setBackground(new java.awt.Color(67, 149, 195));
        SLPV_ekle.setText("Ürün Ekle");
        SLPV_ekle.setMaximumSize(new java.awt.Dimension(140, 80));
        SLPV_ekle.setMinimumSize(new java.awt.Dimension(140, 80));
        SLPV_ekle.setPreferredSize(new java.awt.Dimension(140, 80));
        SLPV_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLPV_ekleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(SLPV_ekle, gridBagConstraints);

        SLPV_yonet.setBackground(new java.awt.Color(67, 149, 195));
        SLPV_yonet.setText("Ürünleri Yönet");
        SLPV_yonet.setMaximumSize(new java.awt.Dimension(140, 80));
        SLPV_yonet.setMinimumSize(new java.awt.Dimension(140, 80));
        SLPV_yonet.setPreferredSize(new java.awt.Dimension(140, 80));
        SLPV_yonet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLPV_yonetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(SLPV_yonet, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void SLPV_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLPV_ekleActionPerformed
        frame.main_anapanel.removeAll();
        frame.main_anapanel.add(new AddStockPanelView());
        frame.main_anapanel.validate();
    }//GEN-LAST:event_SLPV_ekleActionPerformed

    private void SLPV_yonetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLPV_yonetActionPerformed
        frame.main_anapanel.removeAll();
        frame.main_anapanel.add(new ManageStockView());
        frame.main_anapanel.validate();
        
    }//GEN-LAST:event_SLPV_yonetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SLPV_ekle;
    private javax.swing.JButton SLPV_yonet;
    // End of variables declaration//GEN-END:variables
}
