/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

/**
 *
 * @author PaDaWaN
 */
public class StoreLeftPanelView extends javax.swing.JPanel {

    /**
     * Creates new form StatusLeftPanelView
     */
    MainFrame frame;
    public StoreLeftPanelView(MainFrame main) {
        initComponents();
        frame= main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SLPV_ekle = new javax.swing.JButton();
        SLPV_yonet = new javax.swing.JButton();

        SLPV_ekle.setText("Çalışan Ekle");
        SLPV_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLPV_ekleActionPerformed(evt);
            }
        });

        SLPV_yonet.setText("Çalışanları Yönet");
        SLPV_yonet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLPV_yonetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SLPV_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SLPV_yonet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(SLPV_ekle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(SLPV_yonet)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SLPV_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLPV_ekleActionPerformed
        frame.main_anapanel.removeAll();
        frame.main_anapanel.add(new AddEmployeeView());
        frame.main_anapanel.validate();
    }//GEN-LAST:event_SLPV_ekleActionPerformed

    private void SLPV_yonetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLPV_yonetActionPerformed
        frame.main_anapanel.removeAll();
        frame.main_anapanel.add(new ManageEmployeeView());
        frame.main_anapanel.validate();
        
    }//GEN-LAST:event_SLPV_yonetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SLPV_ekle;
    private javax.swing.JButton SLPV_yonet;
    // End of variables declaration//GEN-END:variables
}
