/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;


import com.ada.sme.main.*;
import com.ada.sme.controller.DBController;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PaDaWaN
 */


public class TempAddStockView extends javax.swing.JPanel {

    /**
     * Creates new form TempAddStockView
     */
    MainFrame frame;
    FileReader oin;
    FileWriter oout;
    
    ArrayList<String> sql_list;
    
    public TempAddStockView(MainFrame main) {
        initComponents();
        sql_list=new ArrayList<String>();
        frame= main;
        
        String select_sql;
        
         try {
             
             oin = new FileReader(Main.file);
            BufferedReader reader = new BufferedReader(oin);
    
            
            String tmp;           
            
             DBController dbController = new DBController();
             DefaultTableModel dtm;
             select_sql="SELECT product.product_id,model,quantity,image,price,status FROM product WHERE ";
             
             int flag=0;
             String satir;
             
             while((satir = reader.readLine()) != null){
                tmp = satir;
                sql_list.add(reader.readLine());
                sql_list.add(reader.readLine());
                sql_list.add(reader.readLine());
                sql_list.add(reader.readLine());  
                sql_list.add(reader.readLine());
                sql_list.add(reader.readLine());
                sql_list.add(reader.readLine());
                sql_list.add(reader.readLine());
                
                System.out.print("IDDDDDDDDDD="+tmp+"\n");
                if (flag==0){
                    flag=1;
                    select_sql+="product_id="+tmp+" ";                    
                }else
                    select_sql+="OR product_id="+tmp+" ";
                
        }
      
            
             reader.close();
             System.out.println(select_sql);
             dtm=dbController.selectDB(select_sql);
             TASV_list.setModel(dtm);
        } catch (IOException ex) {
            Logger.getLogger(AddStockPanelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TASV_list = new javax.swing.JTable();
        TASV_yeni = new javax.swing.JButton();
        TASV_kaydet = new javax.swing.JButton();

        TASV_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TASV_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TASV_list);

        TASV_yeni.setText("Yeni Ürün Ekle");
        TASV_yeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TASV_yeniActionPerformed(evt);
            }
        });

        TASV_kaydet.setText("Eklenen Ürünleri Kaydet");
        TASV_kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TASV_kaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TASV_yeni, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TASV_kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TASV_yeni)
                    .addComponent(TASV_kaydet))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TASV_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TASV_listMouseClicked
        String id = TASV_list.getValueAt(TASV_list.getSelectedRow(), 0).toString();
        UpdateStockPanelView updateStockPanelView=new UpdateStockPanelView(id);
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(updateStockPanelView);
        MainFrame.main_anapanel.validate();

    }//GEN-LAST:event_TASV_listMouseClicked

    private void TASV_yeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TASV_yeniActionPerformed
        frame.main_anapanel.removeAll();
        try {
            frame.main_anapanel.add(new AddStockPanelView(frame));
        } catch (IOException ex) {
            Logger.getLogger(StockLeftPanelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.main_anapanel.validate();
    }//GEN-LAST:event_TASV_yeniActionPerformed

    private void TASV_kaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TASV_kaydetActionPerformed
        try {
            DBController db=new DBController();
            for (int i=0;i<sql_list.size();i++){
                db.insDelUpDB(sql_list.get(i));
            }
            oout = new FileWriter(Main.file);
            BufferedWriter bw = new BufferedWriter(oout);
            System.out.print("Yazdım");
            bw.close();
            
            
            
            
            
        } catch (IOException ex) {
            Logger.getLogger(TempAddStockView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_TASV_kaydetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TASV_kaydet;
    private javax.swing.JTable TASV_list;
    private javax.swing.JButton TASV_yeni;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
