/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ada.sme.view;

import com.ada.sme.controller.DBController;
import java.util.ArrayList;

/**
 *
 * @author PaDaWaN
 */
public class UpdateStockPanelView extends javax.swing.JPanel {

    /**
     * Creates new form AddStockPanelView
     */
    
    int res;
    String pro_id;
    public UpdateStockPanelView(String id) {
        initComponents();
        DBController dbController=new DBController();
        ArrayList res;
        res = dbController.selectSingleRowDB("SELECT model,image,weight,minimum,status,price FROM product WHERE product_id="+id);
        USPV_kod.setText(res.get(0).toString());
        USPV_resim.setText(res.get(1).toString());        
        USPV_agirlik.setText(res.get(2).toString());
        USPV_minimum.setText(res.get(3).toString());
        USPV_listele.setSelectedIndex(Integer.parseInt(res.get(4).toString()));
        USPV_fiyat.setText(res.get(5).toString());
        
        res = dbController.selectSingleRowDB("SELECT name,description,tag FROM product_description WHERE product_id="+id);
        USPV_isim.setText(res.get(0).toString());
        USPV_aciklama.setText(res.get(1).toString());
        USPV_etiketler.setText(res.get(2).toString());
        
        res = dbController.selectSingleRowDB("SELECT quantity FROM product_option_value WHERE option_value_id=46 and product_id="+id);
        USPV_adet_s.setText(res.get(0).toString());
        res = dbController.selectSingleRowDB("SELECT quantity FROM product_option_value WHERE option_value_id=47 and product_id="+id);
        USPV_adet_m.setText(res.get(0).toString());
        res = dbController.selectSingleRowDB("SELECT quantity FROM product_option_value WHERE option_value_id=48 and product_id="+id);
        USPV_adet_l.setText(res.get(0).toString());
        
        pro_id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        USPV_kod = new javax.swing.JTextField();
        USPV_isim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        USPV_fiyat = new javax.swing.JTextField();
        USPV_adet_s = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        USPV_resim = new javax.swing.JTextField();
        USPV_guncelle = new javax.swing.JButton();
        USPV_sil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        USPV_adet_l = new javax.swing.JTextField();
        USPV_adet_m = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        USPV_agirlik = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        USPV_minimum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        USPV_listele = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        USPV_aciklama = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        USPV_sil1 = new javax.swing.JButton();
        USPV_etiketler = new javax.swing.JTextField();

        setBackground(new java.awt.Color(227, 227, 227));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ürün bilgilerini Güncelle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(jLabel1, gridBagConstraints);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ürün Kodu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel2, gridBagConstraints);

        USPV_kod.setMaximumSize(new java.awt.Dimension(100, 28));
        USPV_kod.setMinimumSize(new java.awt.Dimension(100, 28));
        USPV_kod.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_kod, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_isim, gridBagConstraints);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ürün İsmi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel3, gridBagConstraints);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ürün Fiyatı:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel4, gridBagConstraints);

        USPV_fiyat.setMaximumSize(new java.awt.Dimension(100, 28));
        USPV_fiyat.setMinimumSize(new java.awt.Dimension(100, 28));
        USPV_fiyat.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_fiyat, gridBagConstraints);

        USPV_adet_s.setText("0");
        USPV_adet_s.setMaximumSize(new java.awt.Dimension(50, 28));
        USPV_adet_s.setMinimumSize(new java.awt.Dimension(50, 28));
        USPV_adet_s.setPreferredSize(new java.awt.Dimension(50, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_adet_s, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ürün Adeti:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel5, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ürün Resmi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel6, gridBagConstraints);

        USPV_resim.setMaximumSize(new java.awt.Dimension(100, 28));
        USPV_resim.setMinimumSize(new java.awt.Dimension(100, 28));
        USPV_resim.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_resim, gridBagConstraints);

        USPV_guncelle.setBackground(new java.awt.Color(67, 149, 195));
        USPV_guncelle.setForeground(new java.awt.Color(254, 254, 254));
        USPV_guncelle.setText("Güncelle");
        USPV_guncelle.setMaximumSize(new java.awt.Dimension(74, 50));
        USPV_guncelle.setMinimumSize(new java.awt.Dimension(74, 50));
        USPV_guncelle.setPreferredSize(new java.awt.Dimension(74, 50));
        USPV_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USPV_guncelleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_guncelle, gridBagConstraints);

        USPV_sil.setBackground(new java.awt.Color(67, 149, 195));
        USPV_sil.setForeground(new java.awt.Color(254, 254, 254));
        USPV_sil.setText("Ürünü Sil");
        USPV_sil.setMaximumSize(new java.awt.Dimension(73, 50));
        USPV_sil.setMinimumSize(new java.awt.Dimension(73, 50));
        USPV_sil.setPreferredSize(new java.awt.Dimension(73, 50));
        USPV_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USPV_silActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_sil, gridBagConstraints);

        jLabel7.setText("Small");
        jLabel7.setToolTipText("");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel7, gridBagConstraints);

        jLabel8.setText("Medium");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel8, gridBagConstraints);

        jLabel9.setText("Large");
        jLabel9.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel9, gridBagConstraints);

        USPV_adet_l.setText("0");
        USPV_adet_l.setMaximumSize(new java.awt.Dimension(50, 28));
        USPV_adet_l.setMinimumSize(new java.awt.Dimension(50, 28));
        USPV_adet_l.setPreferredSize(new java.awt.Dimension(50, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_adet_l, gridBagConstraints);

        USPV_adet_m.setText("0");
        USPV_adet_m.setMaximumSize(new java.awt.Dimension(50, 28));
        USPV_adet_m.setMinimumSize(new java.awt.Dimension(50, 28));
        USPV_adet_m.setPreferredSize(new java.awt.Dimension(50, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_adet_m, gridBagConstraints);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Ürün Ağırlığı(Gr):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel10, gridBagConstraints);

        USPV_agirlik.setMaximumSize(new java.awt.Dimension(100, 28));
        USPV_agirlik.setMinimumSize(new java.awt.Dimension(100, 28));
        USPV_agirlik.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_agirlik, gridBagConstraints);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Minimum:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel11, gridBagConstraints);

        USPV_minimum.setMaximumSize(new java.awt.Dimension(100, 28));
        USPV_minimum.setMinimumSize(new java.awt.Dimension(100, 28));
        USPV_minimum.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_minimum, gridBagConstraints);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Ürünü Listele:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel12, gridBagConstraints);

        USPV_listele.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PASİF", "AKTİF" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_listele, gridBagConstraints);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Açıklama:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel13, gridBagConstraints);

        USPV_aciklama.setColumns(20);
        USPV_aciklama.setRows(5);
        jScrollPane1.setViewportView(USPV_aciklama);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Etiketler:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jLabel14, gridBagConstraints);

        USPV_sil1.setBackground(new java.awt.Color(67, 149, 195));
        USPV_sil1.setForeground(new java.awt.Color(254, 254, 254));
        USPV_sil1.setText("Geri");
        USPV_sil1.setMaximumSize(new java.awt.Dimension(40, 50));
        USPV_sil1.setMinimumSize(new java.awt.Dimension(40, 50));
        USPV_sil1.setPreferredSize(new java.awt.Dimension(40, 50));
        USPV_sil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USPV_sil1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(USPV_sil1, gridBagConstraints);

        USPV_etiketler.setText("asdasdadasdasd");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(USPV_etiketler, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void USPV_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USPV_guncelleActionPerformed
        
        DBController dbController= new DBController();
        int total= Integer.parseInt(USPV_adet_s.getText())+Integer.parseInt(USPV_adet_m.getText())+Integer.parseInt(USPV_adet_l.getText());
        dbController.insProductDB("UPDATE product SET model='"+USPV_kod.getText()+"', price="+USPV_fiyat.getText()+", quantity="+String.valueOf(total)+", image='"+USPV_resim.getText()+"', weight="+USPV_agirlik.getText()+", minimum="+USPV_minimum.getText()+", status="+USPV_listele.getSelectedIndex()+" WHERE product_id="+pro_id);
        dbController.insProductDB("UPDATE product_description SET description='"+USPV_aciklama.getText()+"', tag='"+USPV_etiketler.getText()+"', name='"+USPV_isim.getText()+"' WHERE product_id="+pro_id);
        dbController.insProductDB("UPDATE product_option_value SET quantity="+USPV_adet_s.getText()+" WHERE product_id="+pro_id+" and option_value_id=46");
        dbController.insProductDB("UPDATE product_option_value SET quantity="+USPV_adet_m.getText()+" WHERE product_id="+pro_id+" and option_value_id=47");
        dbController.insProductDB("UPDATE product_option_value SET quantity="+USPV_adet_l.getText()+" WHERE product_id="+pro_id+" and option_value_id=48");
   
    }//GEN-LAST:event_USPV_guncelleActionPerformed

    private void USPV_sil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USPV_sil1ActionPerformed
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(new ManageStockView());
        MainFrame.main_anapanel.validate();
    }//GEN-LAST:event_USPV_sil1ActionPerformed

    private void USPV_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USPV_silActionPerformed
        DBController dbController = new DBController();
        dbController.insProductDB("DELETE FROM product WHERE product_id="+pro_id);
        dbController.insProductDB("DELETE FROM product_description WHERE product_id="+pro_id);
        dbController.insProductDB("DELETE FROM product_option WHERE product_id="+pro_id);
        dbController.insProductDB("DELETE FROM product_option_value WHERE product_id="+pro_id);
        dbController.insProductDB("DELETE FROM product_to_category WHERE product_id="+pro_id);
        dbController.insProductDB("DELETE FROM product_image WHERE product_id="+pro_id);
        
        
        MainFrame.main_anapanel.removeAll();
        MainFrame.main_anapanel.add(new ManageStockView());
        MainFrame.main_anapanel.validate();
    }//GEN-LAST:event_USPV_silActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea USPV_aciklama;
    private javax.swing.JTextField USPV_adet_l;
    private javax.swing.JTextField USPV_adet_m;
    private javax.swing.JTextField USPV_adet_s;
    private javax.swing.JTextField USPV_agirlik;
    private javax.swing.JTextField USPV_etiketler;
    private javax.swing.JTextField USPV_fiyat;
    private javax.swing.JButton USPV_guncelle;
    private javax.swing.JTextField USPV_isim;
    private javax.swing.JTextField USPV_kod;
    private javax.swing.JComboBox USPV_listele;
    private javax.swing.JTextField USPV_minimum;
    private javax.swing.JTextField USPV_resim;
    private javax.swing.JButton USPV_sil;
    private javax.swing.JButton USPV_sil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
